### ISSUE TITLE
Pickup changes of multiple commits - not just the last

### ISSUE THREAD

**Issue by pkyeck** [Tufin/circleci-monorepo#3]
Hi, thanks for the demo-repo - this is really helpful!
I found the link to this repo in the CircleCI forum and I'm running into a similar problem as one user over there:

> Has anyone managed to get around the problem of git diff based on $CIRCLE_COMPARE_URL only showing the changes for the latest commit in a PR?
> Say I create a feature branch and change something in package A, commit and push that, then later discover I had to change something in package B as well. I make changes in package B, commit and push. Now, even when looping over ever package, $(git diff $COMMIT_RANGE --name-only | grep "$PACKAGE") will only show changes for package B, so the first one won’t be tested.

from: https://discuss.circleci.com/t/does-circleci-2-0-work-with-monorepos/10378/19

So, changing something in `service1` and commiting it (but not pushing), then changing something in `service2` and commiting it, leads to this output when running

    $ git diff --no-commit-id --name-only -r `git log -n 2 --oneline --pretty=format:"%h" | tail -n1`
    service2/main.go

The changes in `service1` are not found because they happened in the second to last commit.

Is there a way to check a dynamic range of commits rather than just the last one? We'd need the range since the last test we ran on circleci ...

**Comment by effoeffi** [comment]
@pkyeck fixed, please review
