### ISSUE TITLE
Question about running specific jobs for specific parts of code changed

### ISSUE THREAD

**Issue by tedgonzalez** [Tufin/circleci-monorepo#5]
Hi I was wondering how you are running your tests/jobs in circle ci in your monorepo of project A and B. E.g. only run tests for project A if project A is changed.

Thanks in advance!

**Comment by effoeffi** [comment]
Hi @tedgonzalez,
From readme:

> How does it work?
Everytime you commit a change, it finds the modified files, identifies which directories they reside in, adds dependant directories and calls CircleCI APIs to run builds for these directories.

"run builds for these directories" mean running the service build that defined as part of circleci yaml. Try it... :)
