### ISSUE TITLE
Fails to run

### ISSUE THREAD

**Issue by mathiasi** [Tufin/circleci-monorepo#6]
I forked the repo and pointed CircleCI to it. I have set the CIRCLE_TOKEN with my personal API key.
Fails with

```
jq: error (at <stdin>:2): Cannot index object with number
Exited with code 5
```

**Comment by effoeffi** [comment]
Hi @mathiasi,

This is what we're doing with `CIRCLE_TOKEN`
```
LAST_SUCCESSFUL_BUILD_URL="https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH?filter=completed&limit=1"
LAST_SUCCESSFUL_COMMIT=`curl -Ss -u "$CIRCLE_TOKEN:" $LAST_SUCCESSFUL_BUILD_URL | jq -r '.[0]["vcs_revision"]'`
```
Can you, please, run it locally (after replacing with your vars values) and tell what is the value of `LAST_SUCCESSFUL_BUILD_URL` and `LAST_SUCCESSFUL_COMMIT`?

Note, when you are running a build in circleci it starts with printing the `Using build environment variables`, you can see in there foreach build the env. var. values.

**Comment by mathiasi** [comment]
My bad, I forgot one detail: I forked but ended up putting it on my BitBucket because that's the one I initially authorized with. When I saw your code snippet, I realized that the code is VCS specific. Once I changed all github references to bitbucket in the config, it works.
